/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeCode */

#ifndef _Included_NativeCode
#define _Included_NativeCode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeCode
 * Method:    callCprog
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_NativeCode_callCprog
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
